// Cities/towns grouped by state/UT, keyed by the exact state names in
// indianStates.js (INDIAN_STATES_AND_UTS) so the two stay in sync. Seed
// lists, not exhaustive — India has thousands of towns no fixed list could
// cover, so the City/Town combobox also accepts free text for anything not
// listed here (see Combobox's `allowCustomValue`). Swap this for a real
// city-lookup API later without touching the field itself.
export const CITIES_BY_STATE = {
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Tirupati',
    'Kurnool',
    'Rajahmundry',
    'Kadapa',
  ],
  'Arunachal Pradesh': ['Itanagar', 'Naharlagun', 'Pasighat', 'Tawang', 'Ziro'],
  Assam: ['Guwahati', 'Dibrugarh', 'Silchar', 'Jorhat', 'Tezpur', 'Nagaon'],
  Bihar: ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Darbhanga', 'Purnia'],
  Chhattisgarh: ['Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg'],
  Goa: ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda'],
  Gujarat: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Gandhinagar',
    'Junagadh',
  ],
  Haryana: ['Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Hisar', 'Karnal', 'Rohtak'],
  'Himachal Pradesh': ['Shimla', 'Manali', 'Dharamshala', 'Solan', 'Kullu', 'Mandi'],
  Jharkhand: ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar'],
  Karnataka: [
    'Bengaluru',
    'Mysuru',
    'Hubballi',
    'Mangaluru',
    'Belagavi',
    'Kalaburagi',
    'Shivamogga',
    'Tumakuru',
  ],
  Kerala: [
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Thrissur',
    'Kollam',
    'Kannur',
    'Alappuzha',
  ],
  'Madhya Pradesh': [
    'Bhopal',
    'Indore',
    'Gwalior',
    'Jabalpur',
    'Ujjain',
    'Sagar',
    'Rewa',
    'Satna',
  ],
  Maharashtra: [
    'Mumbai',
    'Pune',
    'Nashik',
    'Nagpur',
    'Kolhapur',
    'Satara',
    'Sangli',
    'Baramati',
    'Solapur',
    'Ahmednagar',
    'Amravati',
    'Aurangabad',
    'Nanded',
    'Thane',
    'Jalgaon',
    'Ratnagiri',
    'Sindhudurg',
    'Latur',
    'Wardha',
    'Chandrapur',
    'Akola',
    'Yavatmal',
    'Beed',
    'Osmanabad',
  ],
  Manipur: ['Imphal', 'Thoubal', 'Bishnupur'],
  Meghalaya: ['Shillong', 'Tura', 'Jowai'],
  Mizoram: ['Aizawl', 'Lunglei', 'Champhai'],
  Nagaland: ['Kohima', 'Dimapur', 'Mokokchung'],
  Odisha: ['Bhubaneswar', 'Cuttack', 'Puri', 'Rourkela', 'Sambalpur', 'Berhampur'],
  Punjab: ['Amritsar', 'Ludhiana', 'Jalandhar', 'Patiala', 'Bathinda', 'Mohali'],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Udaipur',
    'Kota',
    'Ajmer',
    'Bikaner',
    'Alwar',
    'Bharatpur',
  ],
  Sikkim: ['Gangtok', 'Namchi', 'Gyalshing'],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tirunelveli',
    'Vellore',
    'Erode',
  ],
  Telangana: ['Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam'],
  Tripura: ['Agartala', 'Udaipur', 'Dharmanagar'],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Varanasi',
    'Prayagraj',
    'Agra',
    'Meerut',
    'Noida',
    'Ghaziabad',
    'Ayodhya',
    'Mathura',
    'Gorakhpur',
    'Bareilly',
  ],
  Uttarakhand: ['Dehradun', 'Haridwar', 'Rishikesh', 'Nainital', 'Haldwani', 'Roorkee'],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'Siliguri',
    'Durgapur',
    'Asansol',
    'Darjeeling',
  ],
  'Andaman & Nicobar Islands': ['Port Blair'],
  Chandigarh: ['Chandigarh'],
  'Dadra & Nagar Haveli and Daman & Diu': ['Daman', 'Diu', 'Silvassa'],
  Delhi: ['New Delhi', 'Dwarka', 'Rohini', 'Saket', 'Karol Bagh'],
  'Jammu & Kashmir': ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla'],
  Ladakh: ['Leh', 'Kargil'],
  Lakshadweep: ['Kavaratti'],
  Puducherry: ['Puducherry', 'Karaikal', 'Yanam'],
};

export default CITIES_BY_STATE;
